### ISSUE TITLE
Identities.createIdentity returns new Identity with wrong last argument

### ISSUE THREAD

**Issue by Ezerous** [orbitdb/orbit-db-identity-provider#31]
Considering that [the constructor of identity](https://github.com/orbitdb/orbit-db-identity-provider/blob/288dd62c6888cbef38bb46f15afe89bd4212555d/src/identity.js#L5) requires the provider as the last argument, shouldn't the last argument [here](https://github.com/orbitdb/orbit-db-identity-provider/blob/288dd62c6888cbef38bb46f15afe89bd4212555d/src/identities.js#L45) be identityProvider instead of `this`?

**Comment by RichardLitt** [comment]
@Ezerous 	Was this resolved natively, or was there something that you understood such that you thought this could be closed?

**Comment by Ezerous** [comment]
If I remember correctly I just had misunderstood the code.

**Comment by RichardLitt** [comment]
Ah, cool. Just following up, making sure you're not lost. Sorry about the delay! :)
